#!/bin/bash

# -------------------------------------------------------- #

# Place startup programs in this script for stuff that
# executes after Xserver is initialized by xinitrc, or is
# specific to xmonad.

# -------------------------------------------------------- #
# Set default wallpaper - no, using compton and MatrixGL
# instead.  feh --bg-scale "./wallpapers/mystic.png" &

# For lots of screenshots of xscreensavers, see https://www.jwz.org/xscreensaver/screenshots/
# -------------------------------------------------------- #

# -------------------------------------------------------- #
# xscreensaver options
#
#saver="sonar"
# opts for sonar: -ping fosdem.org gnu.org"
# if using sonar you need to setuid of ping by: sudo chmod u+s /usr/lib/xscreensaver/sonar

#saver="phosphor"
#saveropts="-root -window-id WID &"
#saver="starwars"

#saveropts="-program 'cat some_code.txt'"

# examples: glplanet, fireworkx, sonar, star wars, xmatrix, glblur, flame, flurry, atunnel, atlantis, antmaze, dymaxionmap

saver="glmatrix"

# Avoid duplicate processes if this is an xmonad restart.
killall trayer xwinwrap compton "$saver" && sleep 1

# Set the window bars that hold xmobars at top and bottom.
#until [[ !pgrep trayer && !pgrep xwinwrap && !pgrep compton ]] ; do sleep 0.2 ; done
# alpha 0-255 is non-transparent to fully transparent.
trayer --edge top --align left --SetDockType true --SetPartialStrut true --expand true --width 0 --transparent true --alpha 255 --tint 0x000000 --height 10 & 
trayer --edge bottom --align left --SetDockType true --SetPartialStrut true --expand true --width 0 --transparent true --alpha 255 --tint 0x000000 --height 10  &
sleep 1;

# 1 for xscreensaver and 0 for feh
bg="1"
bgimage="wallpaperdefault" #wallpaperdefault is an alias from .bashrc
if [[ $bg == "1" ]] ; then
    # Start the compositor
    compton --shadow-green 1 &
    sleep 1
    # Use a nice xscreensaver background
    xwinwrap -ov -fs -ni -- /usr/lib/xscreensaver/"$saver" -root -window-id WID &
elif [[ bg = "0" ]] ; then
    eval "${bgimage}"
fi

#xwinwrap -ov -fs -ni -- /usr/lib/xscreensaver/"$saver" -ping gnu.org fosdem.org &
#xwinwrap -ov -fs -ni -- /usr/lib/xscreensaver/"$saver" -program 'cat /home/user1/bin/nextcloud-suite.sh/install.sh' -root -window-id WID &

# Set pointer
xsetroot -cursor_name left_ptr &

# Autohide pointer when not using it
unclutter -root -idle 1 &

# Start music server.
mpd &

# Silence all Xorg sounds
xset -b

# Load default X settings.
xrdb -merge .Xdefaults &

# Start a terminal
urxvt &

xscreensaver -no-splash &

# Start xmobar here if it's fucky from xmonadhs
#xmobar ~/.xmonad/xmobarrc &

# Send key combination for toggling struts which is set in
# ~/.xmonad/xmonad.hs xdotool key super+shift+b &

# Load ~/.Xmodmap from here if it doesn't work from
# ~/.xinitrc. Xserver seems to need to be finished initializing;
# adjust sleep seconds accordingly.

sleep 5; /usr/bin/xmodmap /home/user1/.Xmodmap
